### ISSUE TITLE
Units settings

### ISSUE THREAD

**Issue by syborgxx** [woheller69/weather#38]
The user can set units for temperature, distance and can choose Beaufort Scale for winds. I have my app set to use Fahrenheit, miles and Beaufort is off. 

The issue is that precipitation amounts are reported in mm and not inches.

Recommendation to add settings for precipitation units (mm and inch). I also recommend expanding winds to include knots.

**Comment by BradB58** [comment]
Yes, I would really love to see my precipitation in inches please. Thanks.

**Comment by marcofeltmann** [comment]
Shouldn't the app respect the device settings for languages and regional settings and only provide configuration for things like wind speed?

**Comment by woheller69** [comment]
Development of this app has concluded!
OpenWeatherMap has announced that access to One Call 2.5 will be discontinued in June 2024. 
While the app is compatible with One Call 3.0, the subscription requires a credit card, 
even though no payments will be charged due to the 1000 free daily calls. 
I recommend transitioning to my omWeather app, which utilizes data from Open-Meteo, 
as I believe it offers superior information.
