### ISSUE TITLE
App closes automatically after startup

### ISSUE THREAD

**Issue by Squidoid** [woheller69/weather#48]
**Describe the bug**
On first launch, application closes automatically after initial presentation screens, instead of displaying weather conditions. 

**How to Reproduce**
1. Launch application
2. Click on 'Next' 4 times, including the 'Okay' button
3. Application closes automatically without any message

**Expected behavior**
Should display the usual weather information

**Screenshots**
None

**Environment (please complete the following information):**
 - App version: 4.9 (previous version used to work in the same environment)
 - Android version: 12
 - Device: OPPO Find X3 Lite

**Comment by woheller69** [comment]
Bug will be fixed in next version V5.0. Will take a few days for F-Droid to build.
You can either wait (and keep your settings) or use V4.8 in the meantime.

I had "minify" activated in order to reduce app size a bit. But obviously this causes a problem on Android 12.
Android 10 does not seem to have that problem.
