### ISSUE TITLE
Feature Request: Diagram Widget

### ISSUE THREAD

**Issue by marcofeltmann** [woheller69/weather#89]
The diagram is a very useful view to gain quick insights on the expected temperature and rain. It could fully replace the "weather widget 5 day" for some users.

I need to replace TinyWeatherForecastGermany as we move to Spain this year and they only support weather data from Deutscher Wetterdienst (DWD) and used their diagram widget on a daily base.

**Comment by woheller69** [comment]
Development of this app has concluded!
OpenWeatherMap has announced that access to One Call 2.5 will be discontinued in June 2024. 
While the app is compatible with One Call 3.0, the subscription requires a credit card, 
even though no payments will be charged due to the 1000 free daily calls. 
I recommend transitioning to my omWeather app, which utilizes data from Open-Meteo, 
as I believe it offers superior information.
