### ISSUE TITLE
Wind speed in km/h or mph

### ISSUE THREAD

**Issue by rgmf** [woheller69/weather#9]
I just install the app. Congratulations, it' great.

I see the wind speed in bft (I didn't know that unit). I always look at the wind speed in km/h because it has sense for me and it's an important value for me.

I would like to propose you the option of change the unit from bft to km/h when user has selected distance in km and mph if user has selected distance in miles.

What do you think about it?

**Comment by woheller69** [comment]
I am sorry, but I am not planning to add km/h or mph. Others will probably want m/s or knots...
The Beaufort scale gives an impression on the effects a certain wind speed has, like leaves in motion, branches breaking or widespread damage.
I am currently adding a color scheme shown behind the value with yellow, orange, red as warning signs.

It is also better in terms of space on the display.  5 Bft is much more compact than 150 km/h

**Comment by kojid0** [comment]
> I am sorry, but I am not planning to add km/h or mph.

Just wanted to leave a comment here that I am disappointed about this decision. Coming from bigger weather apps like WetterOnline (Germany), I got really used to km/h (default). Over the past years, I really got a feeling what 50 or 70 km/h are like and when things get more dangerous outside. Now I don't have a clue at all...

I'd be very happy if you could re-consider this descision and make an option for km/h (and mph if someones cares). I don't think there's a need for m/s or knots since most people know km/h and mph from daily usage only.

**Comment by woheller69** [comment]
if it is getting dangerous outside you will see this via the yellow, orange, or red background colors introduced in V1.9

**Comment by woheller69** [comment]
km/h and mph will be possible in next version
